name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Instalar o Vercel CLI
      run: |
        npm install -g vercel

    - name: Fazer login no Vercel
      run: |
        vercel login ${{ secrets.VERCEL_TOKEN }}  # Usando um token de autenticação seguro do Vercel

    - name: Deploy para Vercel
      run: |
        vercel --prod --confirm  # Realiza o deploy na Vercel diretamente para o ambiente de produção
